// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tlsConnTuple struct {
	_      structs.HostLayout
	Saddr  [16]uint8
	Daddr  [16]uint8
	Sport  uint16
	Dport  uint16
	Family uint8
	_      [1]byte
}

type tlsEvent struct {
	_         structs.HostLayout
	Pid       uint32
	Tid       uint32
	SslCtx    uint64
	Saddr     [16]uint8
	Daddr     [16]uint8
	DataLen   uint32
	Sport     uint16
	Dport     uint16
	Family    uint8
	Direction uint8
	Data      [16384]uint8
	_         [6]byte
}

type tlsReadCtx struct {
	_          structs.HostLayout
	SslCtx     uint64
	Buf        uint64
	WrittenPtr uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tlsMapActiveReads          = "active_reads"
	tlsMapEvents               = "events"
	tlsMapScratch              = "scratch"
	tlsMapTuples               = "tuples"
	tlsProgKprobeTcpRecvmsg    = "kprobe_tcp_recvmsg"
	tlsProgKprobeTcpSendmsg    = "kprobe_tcp_sendmsg"
	tlsProgUprobeSslRead       = "uprobe_ssl_read"
	tlsProgUprobeSslReadEx     = "uprobe_ssl_read_ex"
	tlsProgUprobeSslWrite      = "uprobe_ssl_write"
	tlsProgUprobeSslWriteEx    = "uprobe_ssl_write_ex"
	tlsProgUretprobeSslRead    = "uretprobe_ssl_read"
	tlsProgUretprobeSslReadEx  = "uretprobe_ssl_read_ex"
	tlsProgUretprobeSslWriteEx = "uretprobe_ssl_write_ex"
)

// loadTls returns the embedded CollectionSpec for tls.
func loadTls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tls: %w", err)
	}

	return spec, err
}

// loadTlsObjects loads tls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsObjects
//	*tlsPrograms
//	*tlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsSpecs struct {
	tlsProgramSpecs
	tlsMapSpecs
	tlsVariableSpecs
}

// tlsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsProgramSpecs struct {
	KprobeTcpRecvmsg    *ebpf.ProgramSpec `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg    *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	UprobeSslRead       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslWrite      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead    *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx  *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslWriteEx *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_ex"`
}

// tlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsMapSpecs struct {
	ActiveReads *ebpf.MapSpec `ebpf:"active_reads"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	Tuples      *ebpf.MapSpec `ebpf:"tuples"`
}

// tlsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsVariableSpecs struct {
}

// tlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsObjects struct {
	tlsPrograms
	tlsMaps
	tlsVariables
}

func (o *tlsObjects) Close() error {
	return _TlsClose(
		&o.tlsPrograms,
		&o.tlsMaps,
	)
}

// tlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsMaps struct {
	ActiveReads *ebpf.Map `ebpf:"active_reads"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	Tuples      *ebpf.Map `ebpf:"tuples"`
}

func (m *tlsMaps) Close() error {
	return _TlsClose(
		m.ActiveReads,
		m.Events,
		m.Scratch,
		m.Tuples,
	)
}

// tlsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsVariables struct {
}

// tlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsPrograms struct {
	KprobeTcpRecvmsg    *ebpf.Program `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg    *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	UprobeSslRead       *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx     *ebpf.Program `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslWrite      *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx    *ebpf.Program `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead    *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx  *ebpf.Program `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslWriteEx *ebpf.Program `ebpf:"uretprobe_ssl_write_ex"`
}

func (p *tlsPrograms) Close() error {
	return _TlsClose(
		p.KprobeTcpRecvmsg,
		p.KprobeTcpSendmsg,
		p.UprobeSslRead,
		p.UprobeSslReadEx,
		p.UprobeSslWrite,
		p.UprobeSslWriteEx,
		p.UretprobeSslRead,
		p.UretprobeSslReadEx,
		p.UretprobeSslWriteEx,
	)
}

func _TlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tls_bpfeb.o
var _TlsBytes []byte
